apiVersion: v1
kind: Service
metadata:
  name: {{ include "knote.fullname" . }}
spec:
  selector:
    app: {{ include "knote.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
