replicaCount: 1

image:
  repository: minio/minio
  tag: RELEASE.2022-10-29T06-21-33Z
  pullPolicy: IfNotPresent

accessKey: mykey
secretKey: mysecret

persistence:
  enabled: true
  size: 256Mi
  storageClass: []

service:
  type: NodePort
  port: 9000
  targetPort: 9000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: minio.local
      paths:
        - path: /minio
          pathType: Prefix
  tls: []

