replicaCount: 1

image:
  repository: minio/minio
  tag: RELEASE.2022-10-29T06-21-33Z
  pullPolicy: IfNotPresent

accessKey: mykey
secretKey: mysecret

persistence:
  enabled: true
  size: 256Mi
  storageClass: gp2

service:
  type: NodePort
  port: 9000
  targetPort: 9000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: a86c26f24bfe54a24896e535e1046f7f-1725809822.eu-north-1.elb.amazonaws.com
      paths:
        - path: /minio
          pathType: Prefix
  tls: []

