apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: storage
spec:
  project: default
  source:
    repoURL: 'https://github.com/Midhun-3/knote.git'
    targetRevision: HEAD
    path: infra/helm/minio
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
